#!/usr/bin/env bash
# Configure Nginx with custom HTTP header

# Update and install Nginx
sudo apt update -y
sudo apt install nginx -y

# Remove existing custom header entries
sudo sed -i '/add_header X-Served-By/d' /etc/nginx/sites-enabled/default

# Add the custom header
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Remove duplicate location directives for /404.html if they exist
sudo sed -i '/location = \/404.html {/,/}/d' /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# If the test is successful, restart Nginx
if [ $? -eq 0 ]; then
    sudo service nginx restart
    echo "Nginx configuration updated and restarted successfully."
else
    echo "Nginx configuration test failed. Please check the configuration."
    exit 1
fi
