#!/usr/bin/env bash
# A play out with processes

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
