#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration
  displays Best School and then Hi on a new line.

r=1

while [ $r -le 10 ]
do
    echo "Best School"
    if [ $r -eq 9 ]
    then
        echo "Hi"
    fi
    ((r++))
done
