#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

_hour=0

while [ $_hour -le 12 ]
do
  echo "_Hour: $_hour"
  _minute=1
  while [ $_minute -le 59 ]
  do
    echo "$_minute"
    (( _minute++ ))
  done
  (( _hour++ ))
done
