#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

_mylist=$(ls)

for r in $_mylist; do
  echo "$r" | cut -d '-' -f2
done
