#!/usr/bin/env bash
# Run Nginx as Nginx
# kill "$(ps auxff | pgrep nginx | head -n 1)"

pkill nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i '/user/s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i '0,/listen \[::\]:80/s/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
sed -i '0,/listen 80/s/listen 80/listen 8080/' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
