#!/usr/bin/env bash
# lines or less
# Changes the user nginx web server is run as

sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '/user/s/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i -e '0,/listen \[::\]:80/s/listen \[::\]:80/listen \[::\]:8080/' -e '0,/listen 80/s/listen 80/listen 8080/' /etc/nginx/sites-available/default
sudo nginx -s /bin/bash -c 'service nginx restart'
