#!/usr/bin/env bash
# Let’s serve what you built for AirBnB clone v3 - RESTful API on web-01.

server {
    listen 80;
    listen [::]:80;
    server_name <your_domain>;

    location /api/ {
        proxy_pass http://127.0.0.1:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
