#!/usr/bin/env bash
# Let’s serve what you built for AirBnB clone - Web dynamic on web-01.

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:5003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /path/to/AirBnB_clone_v4/web_dynamic/static/;
    }

    error_page 404 /404.html;
        location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
